In [1]:
import pandas
import numpy as np
import tensorflow as tf

In [2]:
print(tf.__version__)

1.14.0


In [5]:
link=r"C:\Users\dell\Documents\pincore\Churn_Modelling.csv"
dataset=pandas.read_csv(link)
print(dataset)




      RowNumber  CustomerId         Surname  CreditScore Geography  Gender  \
0             1    15634602        Hargrave          619    France  Female   
1             2    15647311            Hill          608     Spain  Female   
2             3    15619304            Onio          502    France  Female   
3             4    15701354            Boni          699    France  Female   
4             5    15737888        Mitchell          850     Spain  Female   
5             6    15574012             Chu          645     Spain    Male   
6             7    15592531        Bartlett          822    France    Male   
7             8    15656148          Obinna          376   Germany  Female   
8             9    15792365              He          501    France    Male   
9            10    15592389              H?          684    France    Male   
10           11    15767821          Bearce          528    France    Male   
11           12    15737173         Andrews          497     Spa

In [6]:
X=dataset.iloc[:,3:-1].values
Y=dataset.iloc[:,-1].values
print(X)
print(Y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [7]:
from sklearn.preprocessing import LabelEncoder
lr = LabelEncoder()
X[:,2] = lr.fit_transform(X[:,2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X,Y, test_size=0.2, random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [12]:
ann = tf.keras.models.Sequential() #imitating the ANN layers

In [13]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))  #creating the first hidden layer


Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [14]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))  #creating the second hidden layer


In [15]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))  #creating the output layer


In [16]:
ann.compile(optimizer ='adam' , loss= 'binary_crossentropy', metrics = ['accuracy'])  #adam optimizer algo which optimizes error and increases accuracy level, compiling with optimizer

In [17]:
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100)  #epochs 100 telling 100 iterations

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/100
8000/8000 [==============================] - 2s 292us/sample - loss: 0.6766 - acc: 0.5931
Epoch 2/100
8000/8000 [==============================] - 1s 74us/sample - loss: 0.4728 - acc: 0.7946
Epoch 3/100
8000/8000 [==============================] - 1s 76us/sample - loss: 0.4396 - acc: 0.8051
Epoch 4/100
8000/8000 [==============================] - ETA: 0s - loss: 0.4250 - acc: 0.814 - 1s 78us/sample - loss: 0.4276 - acc: 0.8127
Epoch 5/100
8000/8000 [==============================] - 1s 74us/sample - loss: 0.4194 - acc: 0.8169
Epoch 6/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.4119 - acc: 0.8211
Epoch 7/100
8000/8000 [==============================] - 1s 72us/sample - loss: 0.4021 - acc: 0.8239
Epoch 8/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.3905 - acc: 0.8329
Epoch 9/100
8000/8000 [==============================] - 1s

8000/8000 [==============================] - 1s 85us/sample - loss: 0.3333 - acc: 0.8618
Epoch 78/100
8000/8000 [==============================] - 1s 74us/sample - loss: 0.3332 - acc: 0.8652
Epoch 79/100
8000/8000 [==============================] - 1s 74us/sample - loss: 0.3332 - acc: 0.8645
Epoch 80/100
8000/8000 [==============================] - 1s 73us/sample - loss: 0.3332 - acc: 0.8639
Epoch 81/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.3331 - acc: 0.8651
Epoch 82/100
8000/8000 [==============================] - 1s 73us/sample - loss: 0.3327 - acc: 0.8652
Epoch 83/100
8000/8000 [==============================] - 1s 74us/sample - loss: 0.3327 - acc: 0.8652
Epoch 84/100
8000/8000 [==============================] - 1s 75us/sample - loss: 0.3326 - acc: 0.8636
Epoch 85/100
8000/8000 [==============================] - 1s 74us/sample - loss: 0.3329 - acc: 0.8630
Epoch 86/100
8000/8000 [==============================] - 1s 72us/sample - loss: 0.3325 - acc: 

In [18]:
Y_predict = ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))
if(Y_predict > 0.5):
    print("The customer will leave the bank")
else:
    print("The customer will stay with the bank")

The customer will stay with the bank


In [19]:
Y_predict = ann.predict(X_test)
Y_predict = (Y_predict > 0.5)
print(Y_predict, Y_test)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]] [0 1 0 ... 0 0 0]


In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix
print("The accuracy level is = ", accuracy_score(Y_test, Y_predict)*100,"%")
cm = confusion_matrix(Y_test, Y_predict)
print(cm)

The accuracy level is =  86.0 %
[[1506   89]
 [ 191  214]]
