In [1]:
import pandas as pd

In [2]:
ds=pd.read_csv(r"C:\Users\dell\Documents\pincore\50_Startups.csv")
ds.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [3]:
x=ds.iloc[:,0:-1].values
y=ds.iloc[:,-1].values
print(y,x)

[192261.83 191792.06 191050.39 182901.99 166187.94 156991.12 156122.51
 155752.6  152211.77 149759.96 146121.95 144259.4  141585.52 134307.35
 132602.65 129917.04 126992.93 125370.37 124266.9  122776.86 118474.03
 111313.02 110352.25 108733.99 108552.04 107404.34 105733.54 105008.31
 103282.38 101004.64  99937.59  97483.56  97427.84  96778.92  96712.8
  96479.51  90708.19  89949.14  81229.06  81005.76  78239.91  77798.83
  71498.49  69758.98  65200.33  64926.08  49490.75  42559.73  35673.41
  14681.4 ] [[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 9

In [6]:
from sklearn.preprocessing import OneHotEncoder  #to convert character into binary from
from sklearn.compose import ColumnTransformer  #only columns
import numpy as np #we need multiple values
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
#passthrugh means ignore all other which need not be converted
x=np.array(ct.fit_transform(x)) #it transforms the value (required only) and append in array

In [7]:
print(x)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [14]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
y_predict=lr.predict(x_test)

In [16]:
print(y_predict,y_test)

[103015.20159796 132582.27760816 132447.73845174  71976.09851258
 178537.48221055 116161.24230166  67851.69209676  98791.73374686
 113969.43533013 167921.06569551] [103282.38 144259.4  146121.95  77798.83 191050.39 105008.31  81229.06
  97483.56 110352.25 166187.94]


In [17]:
print("Accuracy",lr.score(x,y)*100,'%')

Accuracy 94.8522354717154 %


In [19]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()

In [20]:
lg.fit(x_train,y_train)

C:\Users\dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


ValueError: Unknown label type: 'continuous'

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [10]:
print(x_train)
print(y_train)

[[-0.81649658  1.73205081 -0.73379939 -0.35006454 -0.78547109  0.1011968 ]
 [-0.81649658 -0.57735027  1.36277029 -0.55530319 -1.48117426  0.02734979]
 [-0.81649658  1.73205081 -0.73379939  0.07935762  0.80133381 -0.55152132]
 [ 1.22474487 -0.57735027 -0.73379939 -0.54638238  1.32505817  0.07011684]
 [-0.81649658  1.73205081 -0.73379939  0.43485371 -0.35598663  0.75148516]
 [-0.81649658  1.73205081 -0.73379939  1.26943143  0.85518519  0.98603118]
 [-0.81649658  1.73205081 -0.73379939  1.04525007  1.28077047  0.4404    ]
 [-0.81649658 -0.57735027  1.36277029 -1.529843    0.02942065 -1.6218751 ]
 [-0.81649658 -0.57735027  1.36277029 -1.53976251 -2.76767264 -1.6372965 ]
 [-0.81649658 -0.57735027  1.36277029 -0.13115188  1.14497701 -0.76949991]
 [-0.81649658 -0.57735027  1.36277029  0.92791613 -0.02992062  0.48303162]
 [-0.81649658  1.73205081 -0.73379939 -0.20932933 -0.2993768  -0.89915412]
 [ 1.22474487 -0.57735027 -0.73379939 -0.17870828  0.2251352  -1.26401642]
 [ 1.22474487 -0.57735027

In [11]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

C:\Users\dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


ValueError: Unknown label type: 'continuous'